<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admins' => '',
    'App ID' => '',
    'App Key' => '',
    'Are you sure you want to delete this item?' => '',
    'Auto Message' => '',
    'Auto Post Welcome Message on facebook' => '',
    'Birthday' => '',
    'Close Site Message' => '',
    'Configs' => '',
    'Countries' => '',
    'Country Code' => '',
    'Create' => '',
    'Create Admins' => '',
    'Create Pages' => '',
    'Create Posts' => '',
    'Create Task' => '',
    'Create Users' => '',
    'Date' => '',
    'Delete' => '',
    'Description' => '',
    'Email' => '',
    'Facebook Access' => '',
    'Facebook Email' => '',
    'Facebook Gender' => '',
    'Facebook Id' => '',
    'Facebook Name' => '',
    'Failed' => '',
    'Fb Page' => '',
    'First Name' => '',
    'Gander' => '',
    'HlounPost3' => '',
    'Home AD CODE' => '',
    'Home Message' => '',
    'Home Page Message For Registed Users' => '',
    'ID' => '',
    'Idnow' => '',
    'Is Shared' => '',
    'Isfinish' => '',
    'Keyword' => '',
    'Last Login' => '',
    'Last Name' => '',
    'Last Share' => '',
    'Link' => '',
    'Page ID' => '',
    'Page Name' => '',
    'Pages' => '',
    'Password' => '',
    'Post' => '',
    'Posts' => '',
    'Privacy Policy' => '',
    'Register Date' => '',
    'Register Now' => '',
    'Reset' => '',
    'Search' => '',
    'Site Name' => '',
    'Site Status' => '',
    'Successed' => '',
    'Task For' => '',
    'Tasks' => '',
    'Text' => '',
    'Thank You For Register' => '',
    'Time' => '',
    'Title' => '',
    'Totalcount' => '',
    'Type' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Url' => '',
    'User ID' => '',
    'Users' => '',
    'close' => '',
    'count' => '',
    'posts' => '',
];
